<?php

return [
    'default' => [
        'theme_mode' => 'dark',
        'bg' => '#0a1220',
        'surface' => '#111d2f',
        'surface_alt' => '#182842',
        'panel' => '#0f1b2d',
        'text' => '#e8f2ff',
        'muted' => '#9cb4d1',
        'border' => '#93b6ff33',
        'accent' => '#6ee7ff',
        'accent_strong' => '#4fc3f7',
        'accent_soft' => '#6ee7ff2e',
        'button_start' => '#44d3ff',
        'button_end' => '#5d9bff',
        'button_text' => '#09131c',
        'dropdown_bg' => '#162338',
        'dropdown_text' => '#edf6ff',
        'banner_bg' => '#6ee7ff29',
        'button_radius' => 12,
        'dropdown_radius' => 10,
        'banner_height' => 132,
        'logo_size' => 96,
        'banner_logo' => 'https://example.com/logo.png',
        'panel_title' => 'Neocore',
        'panel_subtitle' => 'Server Control',
    ],
];
